"""
Chat service — business logic for chat / AI assistant operations.

All chat data (sessions and messages) is stored in the app MongoDB database
(``advandeb``) alongside users and other app-level state.

The AI responses are generated by the ``chatbot_agent`` (port 8086), which runs
a full ReAct loop over the bioenergetics knowledge base.

For the streaming WebSocket path, ``process_message_stream`` connects directly
to the chatbot_agent via ``ws://localhost:8086`` using the ``tools/stream``
method, receiving intermediate events (thoughts, tool calls, observations) in
real-time as they are produced by the ReAct loop.

For the non-streaming REST path, ``send_message`` calls the MCP gateway via
``tools/call`` as before.
"""
from __future__ import annotations

import json
import uuid
from typing import AsyncIterator, Dict, Any, List, Optional
from datetime import datetime, timezone
from bson import ObjectId

import websockets  # type: ignore

from advandeb_kb.services.graph_rebuild_queue import graph_rebuild_queue

from app.core.database import get_database
from app.core.config import settings
from app.clients.mcp_client import MCPClient


class ChatService:
    """Service for chat operations — reads/writes app MongoDB database."""

    def __init__(self):
        self.db = get_database()
        self.sessions_collection = self.db.chat_sessions
        self.messages_collection = self.db.chat_messages

    # ------------------------------------------------------------------
    # Streaming WebSocket handler (primary path)
    # ------------------------------------------------------------------

    async def process_message_stream(
        self,
        session_id: str,
        message: str,
        user_id: str,
        llm_config: Optional[Dict[str, Any]] = None,
    ) -> AsyncIterator[Dict[str, Any]]:
        """
        Stream chat events for the WebSocket endpoint.

        Connects directly to chatbot_agent:8086 using the ``tools/stream``
        protocol so each ReAct step (thought, tool call, observation) is
        forwarded to the browser as it happens — not batched at the end.

        When a BYOK provider is selected (``llm_config`` inline from the client,
        or the session's stored config), the provider/model/key_id are passed to
        the agent, which decrypts the key and drives the multi-step ReAct loop
        with the user's own model. The plaintext key never leaves the agent host.

        Emits:
          {"type": "agent_activity", "agent": "chatbot",   "status": "thinking",  "task": "<thought>"}
          {"type": "agent_activity", "agent": "<agent>",   "status": "working",   "task": "<tool>", ...}
          {"type": "agent_activity", "agent": "<agent>",   "status": "completed", "task": "<tool>", "result": "..."}
          {"type": "message", "role": "assistant", "content": "...", "citations": [...], ...}
          {"type": "error", "detail": "..."}
        """
        # Normalise new-session sentinel
        if not session_id or session_id == "new":
            session_id = "new"

        if not settings.MCP_SERVER_ENABLED:
            yield {
                "type": "message",
                "role": "assistant",
                "content": "MCP server is not enabled.",
                "session_id": session_id,
                "suggested_questions": [],
            }
            return

        # Resolve the LLM config: inline (works for brand-new sessions) wins,
        # else the session's stored config.
        config = llm_config or await self.get_session_llm_config(session_id, user_id)

        # Default key path: no user BYOK configured → use operator default key.
        # Uses streaming (answer_stream) so the browser sees tokens as they arrive.
        if self._default_key_applies(config):
            from app.services.byok_chat_service import ByokChatService, ByokSynthesisError
            from app.services.default_chat_rate_limiter import default_rate_limiter

            if not await default_rate_limiter.acquire():
                # Quote the cap actually in force. This message hardcoded
                # "40 req/min" while DEFAULT_CHAT_RPM was 5, so users were told
                # to wait for headroom that was eight times smaller than stated.
                yield {
                    "type": "error",
                    "detail": (
                        f"The shared AI service is temporarily rate-limited "
                        f"({settings.DEFAULT_CHAT_RPM} requests/min shared "
                        f"across all users). Please wait a moment or add your "
                        f"own API key in Settings."
                    ),
                }
                return

            system_prompt = await self.get_session_system_prompt(session_id, user_id)
            try:
                async for chunk in ByokChatService().answer_stream(
                    query=message,
                    session_id=session_id,
                    user_id=user_id,
                    provider=settings.DEFAULT_CHAT_PROVIDER,
                    model=settings.DEFAULT_CHAT_MODEL,
                    direct_api_key=settings.DEFAULT_CHAT_API_KEY,
                    system_prompt=system_prompt,
                ):
                    ctype = chunk.get("type")
                    if ctype in ("status", "_done"):
                        # status/internal events — not forwarded to the browser
                        continue
                    elif ctype == "agent_activity":
                        yield chunk
                    elif ctype == "token":
                        yield chunk
                    elif ctype == "result":
                        graph_rebuild_queue.mark_dirty("chatbot")
                        yield {
                            "type": "message",
                            "role": "assistant",
                            "content": chunk["answer"],
                            "citations": chunk.get("citations", []),
                            "evidence_mode": chunk.get("evidence_mode", "local"),
                            "suggested_questions": chunk.get("suggested_questions", []),
                            "session_id": chunk["session_id"],
                            "message_id": chunk.get("message_id", ""),
                        }
            except ByokSynthesisError as exc:
                yield {"type": "error", "detail": str(exc)}
            return

        # User BYOK key in "final" mode — stream via ByokChatService (KAG pipeline).
        # "react" mode still goes to the chatbot_agent for full ReAct loop support.
        if self._byok_applies(config):
            from app.services.byok_chat_service import ByokChatService, ByokSynthesisError

            system_prompt = await self.get_session_system_prompt(session_id, user_id)
            try:
                async for chunk in ByokChatService().answer_stream(
                    query=message,
                    session_id=session_id,
                    user_id=user_id,
                    provider=config["provider"],
                    key_id=config["key_id"],
                    model=config.get("model"),
                    system_prompt=system_prompt,
                ):
                    ctype = chunk.get("type")
                    if ctype in ("status", "_done"):
                        continue
                    elif ctype == "agent_activity":
                        yield chunk
                    elif ctype == "token":
                        yield chunk
                    elif ctype == "result":
                        graph_rebuild_queue.mark_dirty("chatbot")
                        yield {
                            "type": "message",
                            "role": "assistant",
                            "content": chunk["answer"],
                            "citations": chunk.get("citations", []),
                            "evidence_mode": chunk.get("evidence_mode", "local"),
                            "suggested_questions": chunk.get("suggested_questions", []),
                            "session_id": chunk["session_id"],
                            "message_id": chunk.get("message_id", ""),
                        }
            except ByokSynthesisError as exc:
                yield {"type": "error", "detail": str(exc)}
            return

        arguments: Dict[str, Any] = {
            "query": message,
            "session_id": session_id,
            "user_id": user_id,
            "top_k": 8,
        }
        if config and config.get("key_id") and config.get("provider") not in (None, "", "ollama"):
            arguments["llm_provider"] = config["provider"]
            arguments["llm_key_id"] = config["key_id"]
            if config.get("model"):
                arguments["llm_model"] = config["model"]
        elif config and config.get("model"):
            # Local Ollama path: honour an explicitly selected local model.
            arguments["llm_model"] = config["model"]

        payload = json.dumps({
            "jsonrpc": "2.0",
            "id": str(uuid.uuid4()),
            "method": "tools/stream",
            "params": {
                "name": "chat_stream",
                "arguments": arguments,
            },
        })

        try:
            async with websockets.connect(settings.CHATBOT_AGENT_WS) as ws:
                await ws.send(payload)
                async for raw in ws:
                    try:
                        msg = json.loads(raw)
                    except Exception:
                        continue

                    if "error" in msg:
                        yield {"type": "error", "detail": msg["error"].get("message", "Unknown error")}
                        return

                    if "event" in msg:
                        # Intermediate ReAct event — map to agent_activity
                        event = msg["event"]
                        yield _react_event_to_ws(event)

                    elif "result" in msg:
                        # Final result — emit message event
                        result = msg["result"]
                        actual_sid = result.get("session_id", session_id)
                        citations = await self._enrich_citations(
                            result.get("citations", [])
                        )
                        yield {
                            "type": "message",
                            "role": "assistant",
                            "content": result.get("answer", ""),
                            "citations": citations,
                            "evidence_mode": result.get("evidence_mode", "local"),
                            "suggested_questions": result.get("suggested_questions", []),
                            "session_id": actual_sid,
                            "message_id": result.get("message_id", ""),
                        }
                        return

        except (websockets.WebSocketException, OSError) as exc:
            yield {"type": "error", "detail": f"Could not reach chatbot agent: {exc}"}
            return

    # ------------------------------------------------------------------
    # REST send_message (used by /api/chat/ POST endpoint)
    # ------------------------------------------------------------------

    async def send_message(
        self,
        messages: List[Dict[str, str]],
        session_id: str,
        user_id: str,
    ) -> Dict[str, Any]:
        """Send message and get AI response (non-streaming REST path)."""
        if not session_id:
            session_id = "new"

        last_user = next(
            (m["content"] for m in reversed(messages) if m.get("role") == "user"),
            "",
        )

        byok_config = await self.get_session_llm_config(session_id, user_id)

        # Default key path: no user BYOK → use operator default key.
        if self._default_key_applies(byok_config):
            from app.services.byok_chat_service import ByokChatService, ByokSynthesisError
            from app.services.default_chat_rate_limiter import default_rate_limiter

            if not await default_rate_limiter.acquire():
                return {
                    "message": {
                        "role": "assistant",
                        "content": (
                            "The shared AI service is temporarily rate-limited "
                            "(40 req/min). Please wait a moment or add your own "
                            "API key in Settings."
                        ),
                    },
                    "session_id": session_id,
                    "suggested_questions": [],
                }

            try:
                result = await ByokChatService().answer(
                    query=last_user,
                    session_id=session_id,
                    user_id=user_id,
                    provider=settings.DEFAULT_CHAT_PROVIDER,
                    model=settings.DEFAULT_CHAT_MODEL,
                    direct_api_key=settings.DEFAULT_CHAT_API_KEY,
                )
            except ByokSynthesisError as exc:
                return {
                    "message": {"role": "assistant", "content": f"Error: {exc}"},
                    "session_id": session_id,
                    "suggested_questions": [],
                }
            graph_rebuild_queue.mark_dirty("chatbot")
            return {
                "message": {
                    "role": "assistant",
                    "content": result["answer"],
                    "citations": result["citations"],
                    "evidence_mode": result["evidence_mode"],
                },
                "session_id": result["session_id"],
                "suggested_questions": result.get("suggested_questions", []),
            }

        # BYOK final-answer path: synthesize in-backend with the user's own key.
        if self._byok_applies(byok_config):
            from app.services.byok_chat_service import (
                ByokChatService,
                ByokSynthesisError,
            )

            try:
                result = await ByokChatService().answer(
                    query=last_user,
                    session_id=session_id,
                    user_id=user_id,
                    provider=byok_config["provider"],
                    key_id=byok_config["key_id"],
                    model=byok_config.get("model"),
                )
            except ByokSynthesisError as exc:
                return {
                    "message": {"role": "assistant", "content": f"Error: {exc}"},
                    "session_id": session_id,
                }
            graph_rebuild_queue.mark_dirty("chatbot")
            return {
                "message": {
                    "role": "assistant",
                    "content": result["answer"],
                    "citations": result["citations"],
                    "evidence_mode": result["evidence_mode"],
                },
                "session_id": result["session_id"],
                "suggested_questions": result["suggested_questions"],
            }

        if not settings.MCP_SERVER_ENABLED:
            return {
                "message": {
                    "role": "assistant",
                    "content": "MCP server is not enabled.",
                },
                "session_id": session_id,
            }

        mcp = MCPClient()
        try:
            result = await mcp.call_tool(
                tool_name="chat",
                arguments={
                    "query": last_user,
                    "session_id": session_id,
                    "user_id": user_id,
                    "top_k": 8,
                },
                agent="chatbot_agent",
            )
        except Exception as exc:
            return {
                "message": {
                    "role": "assistant",
                    "content": f"Error: {exc}",
                },
                "session_id": session_id,
            }

        citations = await self._enrich_citations(result.get("citations", []))
        graph_rebuild_queue.mark_dirty("chatbot")
        return {
            "message": {
                "role": "assistant",
                "content": result.get("answer", ""),
                "citations": citations,
                "evidence_mode": result.get("evidence_mode", "local"),
            },
            "session_id": result.get("session_id", session_id),
            "suggested_questions": result.get("suggested_questions", []),
        }

    @staticmethod
    async def _enrich_citations(citations: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Resolve every citation to its source document (best-effort).

        Ensures references coming back from the chatbot agent carry document
        provenance (title/authors/year/url) and not just a bare chunk id.
        """
        if not citations:
            return citations
        from app.services.provenance_service import ProvenanceService
        try:
            return await ProvenanceService().enrich_citations(citations)
        except Exception:  # noqa: BLE001 — never fail the answer over enrichment
            return citations

    # ------------------------------------------------------------------
    # Session management — reads/writes app chat DB
    # ------------------------------------------------------------------

    async def list_sessions(self, user_id: str) -> List[Dict[str, Any]]:
        """List all chat sessions for a user, most recent first."""
        cursor = self.sessions_collection.find(
            {"user_id": user_id},
            {"_id": 1, "title": 1, "created_at": 1, "updated_at": 1},
        ).sort("updated_at", -1)
        sessions = []
        async for session in cursor:
            sessions.append({
                "id": str(session["_id"]),
                "title": session.get("title", ""),
                "created_at": session.get("created_at"),
                "updated_at": session.get("updated_at"),
            })
        return sessions

    async def get_session(
        self, session_id: str, user_id: str
    ) -> Optional[Dict[str, Any]]:
        """Fetch a session and its messages from the app chat database."""
        try:
            oid = ObjectId(session_id)
        except Exception:
            return None

        session = await self.sessions_collection.find_one(
            {"_id": oid, "user_id": user_id}
        )
        if not session:
            return None

        cursor = self.messages_collection.find(
            {"session_id": session_id}
        ).sort("timestamp", 1)

        messages = []
        async for msg in cursor:
            messages.append({
                "id": str(msg["_id"]),
                "role": msg["role"],
                "content": msg["content"],
                "citations": msg.get("citations", []),
                "evidence_mode": msg.get("evidence_mode", "local"),
                "thoughts": msg.get("thoughts", []),
                "status": msg.get("status", "done"),
                "timestamp": msg.get("timestamp"),
            })

        return {
            "id": str(session["_id"]),
            "title": session.get("title", ""),
            "created_at": session.get("created_at"),
            "updated_at": session.get("updated_at"),
            "llm_config": session.get("llm_config"),
            "system_prompt": session.get("system_prompt", ""),
            "messages": messages,
        }

    # ------------------------------------------------------------------
    # Per-session LLM (BYOK) configuration
    # ------------------------------------------------------------------

    async def get_session_llm_config(
        self, session_id: str, user_id: str
    ) -> Optional[Dict[str, Any]]:
        """Return the stored ``llm_config`` for a session, or None."""
        if not session_id or session_id in ("", "new"):
            return None
        try:
            oid = ObjectId(session_id)
        except Exception:
            return None
        doc = await self.sessions_collection.find_one(
            {"_id": oid, "user_id": user_id}, {"llm_config": 1}
        )
        return (doc or {}).get("llm_config")

    async def get_session_system_prompt(
        self, session_id: str, user_id: str
    ) -> Optional[str]:
        """Return the custom system prompt for a session, or None."""
        if not session_id or session_id in ("", "new"):
            return None
        try:
            oid = ObjectId(session_id)
        except Exception:
            return None
        doc = await self.sessions_collection.find_one(
            {"_id": oid, "user_id": user_id}, {"system_prompt": 1}
        )
        return (doc or {}).get("system_prompt") or None

    async def set_session_system_prompt(
        self, session_id: str, user_id: str, system_prompt: str
    ) -> bool:
        """Persist a custom system prompt on the session."""
        try:
            oid = ObjectId(session_id)
        except Exception:
            return False
        result = await self.sessions_collection.update_one(
            {"_id": oid, "user_id": user_id},
            {"$set": {"system_prompt": system_prompt, "updated_at": datetime.now(timezone.utc)}},
        )
        return result.matched_count > 0

    async def set_session_llm_config(
        self, session_id: str, user_id: str, config: Dict[str, Any]
    ) -> bool:
        """Persist a session's ``llm_config`` (provider/mode/model/key_id)."""
        try:
            oid = ObjectId(session_id)
        except Exception:
            return False
        result = await self.sessions_collection.update_one(
            {"_id": oid, "user_id": user_id},
            {"$set": {"llm_config": config, "updated_at": datetime.now(timezone.utc)}},
        )
        return result.matched_count > 0

    @staticmethod
    def _default_key_applies(config: Optional[Dict[str, Any]]) -> bool:
        """True when the operator default API key should be used.

        Triggered by:
        - No session config yet (null) — new user, first message
        - config.provider == "default" — user explicitly chose the default model
        A user BYOK key_id always takes priority over the default.
        Explicit Ollama selection is respected (falls through to the agent).
        """
        if not settings.DEFAULT_CHAT_API_KEY:
            return False
        if not config:
            return True
        return config.get("provider") == "default"

    @staticmethod
    def _byok_applies(config: Optional[Dict[str, Any]]) -> bool:
        """True when a session should be answered by the in-backend BYOK path.

        BYOK handles non-ollama providers in ``final`` mode only. ``react`` mode
        (or an ollama provider) degrades to the standard chatbot_agent path.
        """
        if not config:
            return False
        provider = config.get("provider")
        return (
            bool(config.get("key_id"))
            and provider not in (None, "", "ollama")
            and config.get("mode", "final") != "react"
        )

    async def rename_session(
        self, session_id: str, user_id: str, title: str
    ) -> bool:
        """Rename a chat session."""
        try:
            oid = ObjectId(session_id)
        except Exception:
            return False

        result = await self.sessions_collection.update_one(
            {"_id": oid, "user_id": user_id},
            {"$set": {"title": title, "updated_at": datetime.now(timezone.utc)}},
        )
        return result.matched_count > 0

    async def delete_session(self, session_id: str, user_id: str) -> bool:
        """Delete a session and all its messages."""
        try:
            oid = ObjectId(session_id)
        except Exception:
            return False

        result = await self.sessions_collection.delete_one(
            {"_id": oid, "user_id": user_id}
        )
        if result.deleted_count:
            await self.messages_collection.delete_many({"session_id": session_id})
            return True
        return False


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _react_event_to_ws(event: dict) -> dict:
    """Map a ReactEngine event dict to a frontend agent_activity message."""
    etype = event.get("type", "")
    step = event.get("step", "")
    step_label = f" (step {step})" if step else ""

    if etype == "thought":
        return {
            "type": "agent_activity",
            "agent": "chatbot",
            "status": "thinking",
            "task": event.get("text", ""),
            "step": step,
        }

    if etype == "status":
        # Rich status events emitted by chatbot_agent before/between ReAct steps
        return {
            "type": "agent_activity",
            "agent": event.get("agent", "chatbot"),
            "status": event.get("status", "working"),
            "task": event.get("task", ""),
        }

    if etype == "tool_call":
        return {
            "type": "agent_activity",
            "agent": event.get("agent", "knowledge_agent"),
            "status": "working",
            "task": event.get("tool", "") + step_label,
            "args": event.get("args", {}),
            "step": step,
        }

    if etype == "observation":
        return {
            "type": "agent_activity",
            "agent": event.get("agent", "knowledge_agent"),
            "status": "completed",
            "task": event.get("tool", "") + step_label,
            "result": event.get("summary", ""),
            "step": step,
        }

    if etype == "final_answer":
        return {
            "type": "agent_activity",
            "agent": "chatbot",
            "status": "completed",
            "task": "Final answer ready",
        }

    if etype == "error":
        return {
            "type": "agent_activity",
            "agent": "chatbot",
            "status": "error",
            "task": event.get("message", "Unknown error"),
        }

    # Unknown event type — pass through as generic activity
    return {
        "type": "agent_activity",
        "agent": "chatbot",
        "status": "working",
        "task": str(event),
    }
