"""
Chat service — business logic for chat / AI assistant operations.

All chat data (sessions and messages) is stored in the app MongoDB database
(``advandeb``) alongside users and other app-level state.

The AI responses are generated by the ``chatbot_agent`` (port 8086), which runs
a full ReAct loop over the bioenergetics knowledge base.

For the streaming WebSocket path, ``process_message_stream`` connects directly
to the chatbot_agent via ``ws://localhost:8086`` using the ``tools/stream``
method, receiving intermediate events (thoughts, tool calls, observations) in
real-time as they are produced by the ReAct loop.

For the non-streaming REST path, ``send_message`` calls the MCP gateway via
``tools/call`` as before.
"""
from __future__ import annotations

import json
import uuid
from typing import AsyncIterator, Dict, Any, List, Optional
from datetime import datetime, timezone
from bson import ObjectId

import websockets  # type: ignore

from app.core.database import get_database
from app.core.config import settings
from app.clients.mcp_client import MCPClient


class ChatService:
    """Service for chat operations — reads/writes app MongoDB database."""

    def __init__(self):
        self.db = get_database()
        self.sessions_collection = self.db.chat_sessions
        self.messages_collection = self.db.chat_messages

    # ------------------------------------------------------------------
    # Streaming WebSocket handler (primary path)
    # ------------------------------------------------------------------

    async def process_message_stream(
        self,
        session_id: str,
        message: str,
        user_id: str,
    ) -> AsyncIterator[Dict[str, Any]]:
        """
        Stream chat events for the WebSocket endpoint.

        Connects directly to chatbot_agent:8086 using the ``tools/stream``
        protocol so each ReAct step (thought, tool call, observation) is
        forwarded to the browser as it happens — not batched at the end.

        Emits:
          {"type": "agent_activity", "agent": "chatbot",   "status": "thinking",  "task": "<thought>"}
          {"type": "agent_activity", "agent": "<agent>",   "status": "working",   "task": "<tool>", ...}
          {"type": "agent_activity", "agent": "<agent>",   "status": "completed", "task": "<tool>", "result": "..."}
          {"type": "message", "role": "assistant", "content": "...", "citations": [...], ...}
          {"type": "error", "detail": "..."}
        """
        # Normalise new-session sentinel
        if not session_id or session_id == "new":
            session_id = "new"

        # BYOK final-answer path: synthesize in-backend with the user's own key.
        # No token-level streaming yet — emit a status event, then the answer.
        byok_config = await self.get_session_llm_config(session_id, user_id)
        if self._byok_applies(byok_config):
            from app.services.byok_chat_service import (
                ByokChatService,
                ByokSynthesisError,
            )

            provider = byok_config["provider"]
            yield {
                "type": "agent_activity",
                "agent": "chatbot",
                "status": "working",
                "task": f"Reasoning with your {provider} model…",
            }
            try:
                result = await ByokChatService().answer(
                    query=message,
                    session_id=session_id,
                    user_id=user_id,
                    provider=provider,
                    key_id=byok_config["key_id"],
                    model=byok_config.get("model"),
                )
            except ByokSynthesisError as exc:
                yield {"type": "error", "detail": str(exc)}
                return
            yield {
                "type": "message",
                "role": "assistant",
                "content": result["answer"],
                "citations": result["citations"],
                "evidence_mode": result["evidence_mode"],
                "suggested_questions": result["suggested_questions"],
                "session_id": result["session_id"],
                "message_id": result["message_id"],
            }
            return

        if not settings.MCP_SERVER_ENABLED:
            yield {
                "type": "message",
                "role": "assistant",
                "content": "MCP server is not enabled.",
                "session_id": session_id,
                "suggested_questions": [],
            }
            return

        payload = json.dumps({
            "jsonrpc": "2.0",
            "id": str(uuid.uuid4()),
            "method": "tools/stream",
            "params": {
                "name": "chat_stream",
                "arguments": {
                    "query": message,
                    "session_id": session_id,
                    "user_id": user_id,
                    "top_k": 8,
                },
            },
        })

        try:
            async with websockets.connect(settings.CHATBOT_AGENT_WS) as ws:
                await ws.send(payload)
                async for raw in ws:
                    try:
                        msg = json.loads(raw)
                    except Exception:
                        continue

                    if "error" in msg:
                        yield {"type": "error", "detail": msg["error"].get("message", "Unknown error")}
                        return

                    if "event" in msg:
                        # Intermediate ReAct event — map to agent_activity
                        event = msg["event"]
                        yield _react_event_to_ws(event)

                    elif "result" in msg:
                        # Final result — emit message event
                        result = msg["result"]
                        actual_sid = result.get("session_id", session_id)
                        yield {
                            "type": "message",
                            "role": "assistant",
                            "content": result.get("answer", ""),
                            "citations": result.get("citations", []),
                            "evidence_mode": result.get("evidence_mode", "local"),
                            "suggested_questions": result.get("suggested_questions", []),
                            "session_id": actual_sid,
                            "message_id": result.get("message_id", ""),
                        }
                        return

        except (websockets.WebSocketException, OSError) as exc:
            yield {"type": "error", "detail": f"Could not reach chatbot agent: {exc}"}
            return

    # ------------------------------------------------------------------
    # REST send_message (used by /api/chat/ POST endpoint)
    # ------------------------------------------------------------------

    async def send_message(
        self,
        messages: List[Dict[str, str]],
        session_id: str,
        user_id: str,
    ) -> Dict[str, Any]:
        """Send message and get AI response (non-streaming REST path)."""
        if not session_id:
            session_id = "new"

        last_user = next(
            (m["content"] for m in reversed(messages) if m.get("role") == "user"),
            "",
        )

        # BYOK final-answer path: synthesize in-backend with the user's own key.
        byok_config = await self.get_session_llm_config(session_id, user_id)
        if self._byok_applies(byok_config):
            from app.services.byok_chat_service import (
                ByokChatService,
                ByokSynthesisError,
            )

            try:
                result = await ByokChatService().answer(
                    query=last_user,
                    session_id=session_id,
                    user_id=user_id,
                    provider=byok_config["provider"],
                    key_id=byok_config["key_id"],
                    model=byok_config.get("model"),
                )
            except ByokSynthesisError as exc:
                return {
                    "message": {"role": "assistant", "content": f"Error: {exc}"},
                    "session_id": session_id,
                }
            return {
                "message": {
                    "role": "assistant",
                    "content": result["answer"],
                    "citations": result["citations"],
                    "evidence_mode": result["evidence_mode"],
                },
                "session_id": result["session_id"],
                "suggested_questions": result["suggested_questions"],
            }

        if not settings.MCP_SERVER_ENABLED:
            return {
                "message": {
                    "role": "assistant",
                    "content": "MCP server is not enabled.",
                },
                "session_id": session_id,
            }

        mcp = MCPClient()
        try:
            result = await mcp.call_tool(
                tool_name="chat",
                arguments={
                    "query": last_user,
                    "session_id": session_id,
                    "user_id": user_id,
                    "top_k": 8,
                },
                agent="chatbot_agent",
            )
        except Exception as exc:
            return {
                "message": {
                    "role": "assistant",
                    "content": f"Error: {exc}",
                },
                "session_id": session_id,
            }

        return {
            "message": {
                "role": "assistant",
                "content": result.get("answer", ""),
                "citations": result.get("citations", []),
                "evidence_mode": result.get("evidence_mode", "local"),
            },
            "session_id": result.get("session_id", session_id),
            "suggested_questions": result.get("suggested_questions", []),
        }

    # ------------------------------------------------------------------
    # Session management — reads/writes app chat DB
    # ------------------------------------------------------------------

    async def list_sessions(self, user_id: str) -> List[Dict[str, Any]]:
        """List all chat sessions for a user, most recent first."""
        cursor = self.sessions_collection.find(
            {"user_id": user_id},
            {"_id": 1, "title": 1, "created_at": 1, "updated_at": 1},
        ).sort("updated_at", -1)
        sessions = []
        async for session in cursor:
            sessions.append({
                "id": str(session["_id"]),
                "title": session.get("title", ""),
                "created_at": session.get("created_at"),
                "updated_at": session.get("updated_at"),
            })
        return sessions

    async def get_session(
        self, session_id: str, user_id: str
    ) -> Optional[Dict[str, Any]]:
        """Fetch a session and its messages from the app chat database."""
        try:
            oid = ObjectId(session_id)
        except Exception:
            return None

        session = await self.sessions_collection.find_one(
            {"_id": oid, "user_id": user_id}
        )
        if not session:
            return None

        cursor = self.messages_collection.find(
            {"session_id": session_id}
        ).sort("timestamp", 1)

        messages = []
        async for msg in cursor:
            messages.append({
                "id": str(msg["_id"]),
                "role": msg["role"],
                "content": msg["content"],
                "citations": msg.get("citations", []),
                "evidence_mode": msg.get("evidence_mode", "local"),
                "thoughts": msg.get("thoughts", []),
                "status": msg.get("status", "done"),
                "timestamp": msg.get("timestamp"),
            })

        return {
            "id": str(session["_id"]),
            "title": session.get("title", ""),
            "created_at": session.get("created_at"),
            "updated_at": session.get("updated_at"),
            "llm_config": session.get("llm_config"),
            "messages": messages,
        }

    # ------------------------------------------------------------------
    # Per-session LLM (BYOK) configuration
    # ------------------------------------------------------------------

    async def get_session_llm_config(
        self, session_id: str, user_id: str
    ) -> Optional[Dict[str, Any]]:
        """Return the stored ``llm_config`` for a session, or None."""
        if not session_id or session_id in ("", "new"):
            return None
        try:
            oid = ObjectId(session_id)
        except Exception:
            return None
        doc = await self.sessions_collection.find_one(
            {"_id": oid, "user_id": user_id}, {"llm_config": 1}
        )
        return (doc or {}).get("llm_config")

    async def set_session_llm_config(
        self, session_id: str, user_id: str, config: Dict[str, Any]
    ) -> bool:
        """Persist a session's ``llm_config`` (provider/mode/model/key_id)."""
        try:
            oid = ObjectId(session_id)
        except Exception:
            return False
        result = await self.sessions_collection.update_one(
            {"_id": oid, "user_id": user_id},
            {"$set": {"llm_config": config, "updated_at": datetime.now(timezone.utc)}},
        )
        return result.matched_count > 0

    @staticmethod
    def _byok_applies(config: Optional[Dict[str, Any]]) -> bool:
        """True when a session should be answered by the in-backend BYOK path.

        BYOK handles non-ollama providers in ``final`` mode only. ``react`` mode
        (or an ollama provider) degrades to the standard chatbot_agent path.
        """
        if not config:
            return False
        provider = config.get("provider")
        return (
            bool(config.get("key_id"))
            and provider not in (None, "", "ollama")
            and config.get("mode", "final") != "react"
        )

    async def rename_session(
        self, session_id: str, user_id: str, title: str
    ) -> bool:
        """Rename a chat session."""
        try:
            oid = ObjectId(session_id)
        except Exception:
            return False

        result = await self.sessions_collection.update_one(
            {"_id": oid, "user_id": user_id},
            {"$set": {"title": title, "updated_at": datetime.now(timezone.utc)}},
        )
        return result.matched_count > 0

    async def delete_session(self, session_id: str, user_id: str) -> bool:
        """Delete a session and all its messages."""
        try:
            oid = ObjectId(session_id)
        except Exception:
            return False

        result = await self.sessions_collection.delete_one(
            {"_id": oid, "user_id": user_id}
        )
        if result.deleted_count:
            await self.messages_collection.delete_many({"session_id": session_id})
            return True
        return False


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _react_event_to_ws(event: dict) -> dict:
    """Map a ReactEngine event dict to a frontend agent_activity message."""
    etype = event.get("type", "")
    step = event.get("step", "")
    step_label = f" (step {step})" if step else ""

    if etype == "thought":
        return {
            "type": "agent_activity",
            "agent": "chatbot",
            "status": "thinking",
            "task": event.get("text", ""),
            "step": step,
        }

    if etype == "status":
        # Rich status events emitted by chatbot_agent before/between ReAct steps
        return {
            "type": "agent_activity",
            "agent": event.get("agent", "chatbot"),
            "status": event.get("status", "working"),
            "task": event.get("task", ""),
        }

    if etype == "tool_call":
        return {
            "type": "agent_activity",
            "agent": event.get("agent", "knowledge_agent"),
            "status": "working",
            "task": event.get("tool", "") + step_label,
            "args": event.get("args", {}),
            "step": step,
        }

    if etype == "observation":
        return {
            "type": "agent_activity",
            "agent": event.get("agent", "knowledge_agent"),
            "status": "completed",
            "task": event.get("tool", "") + step_label,
            "result": event.get("summary", ""),
            "step": step,
        }

    if etype == "final_answer":
        return {
            "type": "agent_activity",
            "agent": "chatbot",
            "status": "completed",
            "task": "Final answer ready",
        }

    if etype == "error":
        return {
            "type": "agent_activity",
            "agent": "chatbot",
            "status": "error",
            "task": event.get("message", "Unknown error"),
        }

    # Unknown event type — pass through as generic activity
    return {
        "type": "agent_activity",
        "agent": "chatbot",
        "status": "working",
        "task": str(event),
    }
